name: Build iOS Swift App
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile Swift App
        run: |
          swiftc -target arm64-apple-ios15.0 "Sources/First App/First_App.swift" -o MyApp.ipa
      - name: Upload App Asset
        uses: actions/upload-artifact@v4
        with:
          name: iPhoneApp
          path: MyApp.ipa
